# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-05 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='product',
        ),
        migrations.AddField(
            model_name='profile',
            name='product',
            field=models.ManyToManyField(to='shop.Product'),
        ),
    ]
